### ISSUE TITLE
Add my interpretability-friendly models to HuggingFace

### ISSUE THREAD

**Issue by neelnanda-io** [neelnanda-io/TransformerLens#102]
Add my interpretability-friendly models to HuggingFace (documented here: https://docs.google.com/document/d/1WONBzNqfKIxERejrrPlQMyKqg7jSFW92x5UMXNrMdPo/edit#heading=h.chq47zvs9cii )

This probably looks like adding the HookedTransformer + HookedTransformerConfig class to HuggingFace AutoModel, I'm not super sure how it works. Ideally this would be able to slot into code using HuggingFace models to eg evaluate them or generate text.

(Not actually a TransformerLens issue per se, but useful!)

**Comment by alan-cooney** [comment]
This was done a while ago
