### ISSUE TITLE
Cache common model weights (eg post LN folding) to shorten model loading times.

### ISSUE THREAD

**Issue by neelnanda-io** [neelnanda-io/TransformerLens#103]
Not sure exactly what the best way to cache is, I'd try to copy how HuggingFace transformers does it. The easiest way might be to just create a separate model on HuggingFace with the post processing weights and to pull the weights from that 

Probably best to cache a version with all the default flags to `from_pretrained` and just use that by default, otherwise use the existing loading code.

I'd do this for small-ish and important models, eg all 4 GPT-2s and my interpretability friendly models.

**Comment by glerzing** [comment]
Isn't this issue obsolete ?
I suggest to make a quick check of all the issues, and close the ones that are not relevant anymore.
