### ISSUE TITLE
Add support for model parallelism

### ISSUE THREAD

**Issue by neelnanda-io** [neelnanda-io/TransformerLens#105]
Add support for having a model with layers split across several GPUs.

Make sure the layers (and its HookPoints) know what device they're on, so that hooks can ensure that they aren't needlessly moving information between GPUs. ActivationCache is a dictionary and _should_ work by default.

The MVP would be doing 2 GPUs: putting the embed + first half of layers on GPU 1 and the second half + unembed on GPU 2. This is probably the most that's needed to support eg NeoX? 

I'm not sure of the most elegant way of doing this, or how to do this without making the code really messy. I lean towards either adding a method which edits the model to move layers between devices, or making a separate `ParallelHookedTransformer` class

**Comment by anshradh** [comment]
To be clear: you're looking for support of Pipeline Parallelism, rather than e.g. Tensor Parallelism?

**Comment by neelnanda-io** [comment]
Yeah, pipeline (ie each layer on a single GPU). It seems very important
that an activation is on a single GPU, so hooks can kinda function as
before, just ensuring they act on the correct device. Activations split
across GPUs sounds horrifying. I think this is worth taking a decent
performance hit for.

**Comment by anshradh** [comment]
Yeah agreed tensor parallelism seems pretty cursed.

I'd be interested in taking this on, my proposed implementation would likely involve the user passing the number of devices they want to load the model on and then figuring out the distribution of layers from there (e.g num_devices = 4 for gpt-2-small
-> embed and layers 0-2 on gpu 0, layers 3-5 on gpu 1, layers 6-8 on gpu 2, layers 9-11 and unembed on gpu 3.)

Seems like it would be also nice to support something like gpipe to speed up training (basically just split up minibatches further and do gradient accumulation, should be simple enough).

**Comment by neelnanda-io** [comment]
That API seems pretty reasonable to me! Supporting just a forward pass is
probably fine, and supporting efficient training seems like probably
overkill, until and unless anyone wants to start using this feature for
something hardcore and large scale. TransformerLens is *not *designed to
train 20B models!

**Comment by jbloomAus** [comment]
Tasks required to complete this issue:

- [ ] https://github.com/neelnanda-io/TransformerLens/issues/246

May add more if we decide the model parallelism requires other enhancements not yet obvious.

**Comment by jbloomAus** [comment]
Solved due to #250  solving that last issue.
