### ISSUE TITLE
Add evals for algorithmic-ish tasks like Indirect Object Identification

### ISSUE THREAD

**Issue by neelnanda-io** [neelnanda-io/TransformerLens#106]
Add to `evals.py` support for checking how good a model is at tasks like [Indirect Object Identification](https://arxiv.org/abs/2211.00593). Notably, where the eval involves generating a synthetic dataset of names, as they do in the paper (can copy from [their codebase](https://github.com/redwoodresearch/Easy-Transformer)), running the model on them, and returning the average logit diff and accuracy. 

Bonus:
* Add support for prompts of different token length 
* Support multi-token answers.
* Write this in a generic way, where any generated dataset can be subbed in
* Give an option to pair up prompts, so "John and Mary went to the store, John gave the bag to" is followed by "John and Mary went to the store, Mary gave the bag to", to avoid biases where the model just favours common names

**Comment by jbloomAus** [comment]
Closed by #198
