### ISSUE TITLE
Add a permanent hooks feature to HookPoint, that isn't deleted when you run `model.reset_hooks()`

### ISSUE THREAD

**Issue by neelnanda-io** [neelnanda-io/TransformerLens#113]
Currently, running `run_with_hooks` or `run_with_cache` ends by running `model.reset_hooks()`, which deletes *all* hooks. This means that if I, eg, want to [create a model without positional embeddings](https://www.youtube.com/watch?v=yo4QvDn-vsU), I can't add a hook that just sets `pos_embed` to zero, without breaking `run_with_hooks` or `run_with_cache`. The underlying problem is that PyTorch hooks are global state, but I want `run_with_*` to present them as local state to the user.

I'd like to add an `add_perma_hook` method to a `HookPoint`, which tracks hooks separately from `add_hook`, so that `reset_hooks` only deletes the normal hooks and not the perma-hooks (essentially creating a separate class of global state hooks and local state hooks)

**Comment by derpyplops** [comment]
I'll take a look at this

**Comment by neelnanda-io** [comment]
Thanks so much! Let me know if you need any tips
