### ISSUE TITLE
Issues setting up dev environment

### ISSUE THREAD

**Issue by derpyplops** [neelnanda-io/TransformerLens#118]
I've been having issues setting up my dev environment.

 OS: MacOS Monterey
  Model Name:	MacBook Air
  Model Identifier:	Mac14,2
  Chip:	Apple M2

## What I was doing

- I cloned the repo
- ran `poetry config virtualenvs.in-project true` and `poetry install --with dev`
- after the last command, I got
![image](https://user-images.githubusercontent.com/29353832/208961972-553377a6-d3cc-4da4-8ffd-21f9d4bb6475.png)

## What I tried to fix it
1. Upgrading pytorch
- Change pytorch version to 1.13.1
- This produced a new error, [stack trace](https://github.com/neelnanda-io/TransformerLens/files/10279732/log.txt)

2. Installing in a docker container
```
FROM ubuntu:latest

RUN apt-get -yqq update
RUN apt-get -yqq install git

RUN apt-get -yqq install python3    
RUN apt-get -yqq install python3-pip
RUN apt-get -yqq update

RUN git clone https://github.com/neelnanda-io/TransformerLens.git

WORKDIR /TransformerLens

RUN pip3 install poetry
RUN poetry config virtualenvs.in-project true
# RUN poetry install --with dev
```

This produced the same `nvidia-cudnn-cu11` errors as before, which did not change even after I tried bumping the pytorch version.

**Comment by neelnanda-io** [comment]
@alan-cooney Any idea what's up with this:

**Comment by neelnanda-io** [comment]
But also, huh! Fascinating. What system is this on? And does runnin PyTorch normally work?

What if you do `pip install -e PATH_NAME` ? (Which is how I'm installing it)

**Comment by alan-cooney** [comment]
Is this in a notebook? It may be that you're using a different venv in vscode, than the one that you've installed the packages into.

Btw - we'll have a pypi version in the next few days (so you can just pip install it into your project), and I'll also add a docker image for dev work (but note that docker + cuda is a notoriously janky combination)

**Comment by alan-cooney** [comment]
Should now work with `pip install transformer-lens` in your own repo (and the devcontainer should fix the other issue)
