### ISSUE TITLE
"is not divisible" / "is not equal confusion"

### ISSUE THREAD

**Issue by joelburget** [neelnanda-io/TransformerLens#120]
These lines test for equality but the error message is about divisibility:

https://github.com/neelnanda-io/TransformerLens/blob/c0f1c0e473f6cd1a4ca189af54818d6b64342b7c/transformer_lens/HookedTransformerConfig.py#L162-L165

This can lead to the misleading error message "d_model=16 is not divisible by n_heads=2 * d_head=4".

I'm guessing the check should change but I'm not sure.

**Comment by neelnanda-io** [comment]
Good point, fixed.
