### ISSUE TITLE
Add Auto-Generated Documentation

### ISSUE THREAD

**Issue by neelnanda-io** [neelnanda-io/TransformerLens#132]
Add something like Read The Docs to auto-generate docs

Bonus: Clean up docstrings so things aren't a mess

**Comment by untoldj** [comment]
Hello,
I have begun working on this as a small personal project in order to gain more experience with Read The Docs. If you're interested in my help or seeing what I have accomplished on this so far, please let me know.

**Comment by neelnanda-io** [comment]
Awesome, thanks so much! This was on my to-do list for things I wanted to get done before officially releasing the library, which I'd hoped to do in the next 1-3 weeks, so I was considering doing a rough MVP myself - any idea how hard this is/how long this might take you? (I don't want you to feel pressure to commit to this or do it fast, but also want to avoid a world where I leave this for you to do, and this blocks releasing the library)

**Comment by untoldj** [comment]
I guess it depends on how clean and feature-filled you want the docs to be. I have basically all of the text and sample code from the demo Jupyter notebook (assuming that's what you wanted to use for the documentation) up on Read the Docs. They just require some cleanup. At the moment, there are some remnants from the Jupyter notebook (things like {.cell .markdown}) that I need to go through and edit out. I haven't really modified the docs at all besides some formatting, but I plan to go through and edit some of the longer paragraphs for conciseness. Also, it's still all on one page at the moment, but the left-side navbar allows you to jump between the different headings. Adding the interactive graphs from the notebook and such might require a bit more time. Let me know if you'd like the link to what I have so far, and you can give me any feedback you like. I'm currently using Markdown with Myst-Parser to convert it to HTML.

**Comment by neelnanda-io** [comment]
Oh, working but somewhat messy is completely fine by me, that all sounds
great! I'd love a link to what you have so far. Thanks a lot for the help :)

**Comment by untoldj** [comment]
Here's a link. https://transformerlens-jdbowma.readthedocs.io/en/latest/index.html
Hopefully this is somewhere along the lines of what you were looking for. It should be really simple to add more docs.

**Comment by neelnanda-io** [comment]
Thanks! How hard is it to auto generate docs from the docstring in the
code? I like having an abridged version of the tutorial as the docs (which
you basically have at the moment), but also want to have a reference for
what functions do (idk how much work it is to generate that, or how much
the code would need to be editing to get reasonable doc strings).

I'm generally interested in ways to auto-generate docs from the code or
demos, so that the docs don't get super stale over time.

**Comment by jdbowma** [comment]
My bad for the late response.

I haven't totally looked into that yet, I'll see if I can figure it out. I'll let you know if I am able to do that. This should be fairly easy to do as the auto-generation of docs is basically the purpose of Read the Docs, but from what I understand it needs to have markdown files to display the text, so at some level, you'd probably need to generate markdown from the docstrings. Again, I could be wrong so I'll check it out later tonight to see how simple this would be.

Again, apologies for the delay.

**Comment by jdbowma** [comment]
https://sphinx-rtd-tutorial.readthedocs.io/en/latest/build-the-docs.html#generating-documentation-from-docstrings

I believe this is the answer to our problem right here. Shouldn't be difficult at all to get that up and running.

**Comment by jbloomAus** [comment]
@jdbowma you're right that this should make autogenerating docs easy. It would be good to create a PR, although you're branch might be a little diverged (24 commits behind main). Would you be able to rebase and submit a PR? I can help if needed.

**Comment by jbloomAus** [comment]
@neelnanda-io  I've made a branch with autogenerating documentation.

You can preview it here: https://jbloomaus.github.io/TransformerLens/
and the code here: https://github.com/jbloomAus/TransformerLens/tree/sphinx-documenation

Stuff I've done:
- Set up a sphinx documentation with extensions to read docstrings nicely and work off markdown files 
- Set up a github action to compile the documentation and then automatically generate.
- It's possibly to automatically see the documentation regenerate as you develop.

Stuff I haven't done but is possible:
- automatically including all the .ipynb files.
- added a nice logo/graphics/images/favicon anywhere

I'd love your thoughts. I think a logo/images/a little more work on the docs might be justified. Don't want to decide the logo for you though. 

@jdbowma sorry I didn't wait. Plenty to do if you want to help though!
