### ISSUE TITLE
pre-commit in requirements?

### ISSUE THREAD

**Issue by jas-ho** [neelnanda-io/TransformerLens#150]
Hi @neelnanda-io , do you want to have pre-commit in the requirements? If so, I could add that
or is the pre-commit-config.yml obsolete?

**Comment by neelnanda-io** [comment]
That is a great question! Er, I think it's no longer required? We were
using it for nbdev, which we don't really bother with any more.

I appreciate all the issues btw! Useful to get data on what confuses
beginners to the library with programming experience

**Comment by jas-ho** [comment]
cool to hear these comments are not just noise :) 
this specific case here was in the spirit of "I'd like to contribute to this repo and want to be sure I respect the code conventions"

**Comment by jas-ho** [comment]
if you don't expect people to run precommit when contributing I'd remove the `pre-commit-config.yml`

**Comment by neelnanda-io** [comment]
Point, deleted. @alan-cooney Just checking I'm not missing anything dumb here?

**Comment by alan-cooney** [comment]
Yep makes sense to get rid of it
