### ISSUE TITLE
Some OPT Tokenizer Confusion

### ISSUE THREAD

**Issue by afspies** [neelnanda-io/TransformerLens#153]
Hi,

When trying to use `utils.test_prompt` with an OPT model I am running into issues surrounding the prepending of BOS tokens. In particular, I think the call to `PreTrainedTokenizerBase` sets `add_special_tokens` to true, regardless of the `prepend_base` flag in `model.to_str_tokens`, which leads to at least one `</s>` being preprended (and if `prepend_base=True`, then two are prepended). 

For example:

```
prompt: "Two young, White males are outside near many bushes"
# Split into prompt = "Two young .... many", answer = "bushes"
Tokenized prompt: ['</s>', '</s>', 'Two', ' young', ',', ' White', ' males', ' are', ' outside', ' near', ' many']
Tokenized answer: ['</s>', ' bushes', '.', '\n']
```

I am not sure if this is the desired behaviour for OPT?

Even if it is, I think the utils.test_prompt needs to be adjusted to expect the `</s>` at the beginning of the tokenized answer, in this case.

Happy to make these changes once you confirm what the expected behaviour is.

Thanks!

**Comment by neelnanda-io** [comment]
Huh, honestly I've never actually used the OPT models for something serious. My understanding is that they were trained to expect a BOS token, _and_ that their tokenizers will automatically prepend that. Currently, HookedTransformer assumes that the tokenizer does _not_ prepend a BOS, and will explicitly prepend one. This is clearly a bug.

IMO the best way to do this is to remove the OPT tokenizer's automatic prepending of a BOS token, and then the existing code should all just work. In particular, `model.to_tokens(string, prepend_bos=False)` _should_ give the user something without a BOS! 

This does come at the cost of users shooting themselves in the foot if they manually disable the BOS, but w/e this seems fine. This is consistent with how my SoLU + toy models work (trained with a BOS, but the tokenizer does not prepend it automatically, while `to_tokens` and `to_str_tokens` does.

**Comment by afspies** [comment]
Ok that's what I thought :) 

Will change this later.

On a side note, is there any reason to disregard OPT for mech.int. analysis, or is it just that GPT is sufficiently fruitful as a target? (I am concerned about generality!)

**Comment by neelnanda-io** [comment]
No particular reason, there's just a lot of models in TL lol. I default to
GPT-2, or to my toy models or SoLU models. If I want to check various
things, the Stanford models (GPT-2 Medium or Small for 5 random seeds) are
my default there. GPT-J is my default if I want a bigger model.

OPT is weird because as far as I'm aware, the models aren't actually very
good, trained for 180B tokens, and it has ReLU activations, but there's no
strong reason to *not* use it. And TL is designed so code is easy to run
across a ton of models by just changing the name in from_pretrained

**Comment by afspies** [comment]
Good to know! Have hopefully fixed this now.
