### ISSUE TITLE
Convert all TorchTyping to JaxTyping

### ISSUE THREAD

**Issue by neelnanda-io** [neelnanda-io/TransformerLens#164]
This project uses Patrick Kidger's torch typing to give tensor types including shapes. He recommends using JAXTyping for newer projects (not JAX specific, better maintained, more compatible with type checkers, etc) And it'd be good to update TL to use it. 

@dkamm might be up your alley? Sorry if this invalidates your enum work, but might be a more elegant solution!

**Comment by neelnanda-io** [comment]
Hopefully addresses #155

**Comment by dkamm** [comment]
@neelnanda-io Happy to check it out! And no worries, I'm all for dropping it for something better :)
