### ISSUE TITLE
Two issues with tests

### ISSUE THREAD

**Issue by ArthurConmy** [neelnanda-io/TransformerLens#167]
As discussed here https://github.com/neelnanda-io/TransformerLens/pull/161 , currently the testing

i) does not provide signal on which tests are failing
ii) seems to be incorrect? They pass locally for me

I'm a bit busy to do the good honest engineering required to improve this ATM :(

**Comment by neelnanda-io** [comment]
Weird!

Observation 1: _I_ can see results of the tests, but I guess this is only something I can see? This seems like it should be configurable, but I can't see anything obvious (@alan-cooney ?)

Observation 2: The failure message for the tests here makes no sense, it just says "test was cancelled", while it normally gives the error message from the tests.

Overall idk, problem 1 seems valuable to fix, problem 2 seems like maybe a weird one-off bug:

**Comment by ArthurConmy** [comment]
Yeah I also get the test cancelled thing:

https://i.imgur.com/KCKwxL7.png

However, since there are 10 dots (I think!) after `test_transformer_lens`, my impression was the failure occurred during that last test...? If so, there should be some message that says where this fails

**Comment by alan-cooney** [comment]
Unfortunately when PyTest runs out of memory it throws this non-descript error (otherwise it would tell you which test failed).

Looks like it is fixed in the underlying PR, so I'm going to close this for now, but feel free to re-open if necessary.
