### ISSUE TITLE
Cannnot install dependencies via poetry (y-py-0.5.5 is yanked)

### ISSUE THREAD

**Issue by rusheb** [neelnanda-io/TransformerLens#177]
I'm trying to install the project via `poetry install` for python 3.9.

I get this error:
```
  PoetryException

  Failed to install /Users/rusheb/Library/Caches/pypoetry/artifacts/be/5d/9c/38ed00c38e66f11b3f1295c0b4fa2565c954b8e0c8d63deac26e996efa/y_py-0.5.5.tar.gz

  at /opt/homebrew/lib/python3.10/site-packages/poetry/utils/pip.py:58 in pip_install
       54│
       55│     try:
       56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
    →  58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       59│

  • Installing yarl (1.8.2)
Warning: The file chosen for install of y-py 0.5.5 (y_py-0.5.5.tar.gz) is yanked. Reason for being yanked: Inconsistent wheels
```

Output of poetry env info:
```
❯ poetry env info

Virtualenv
Python:         3.9.16
Implementation: CPython
Path:           /Users/rusheb/code/TransformerLens/.venv
Executable:     /Users/rusheb/code/TransformerLens/.venv/bin/python
Valid:          True
```

Also, I saw this warning at the top of the poetry install output:
```
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.
```

I think running `poetry lock` should fix it. I'll try to raise a fix now.

**Comment by rusheb** [comment]
I was wondering why this wasn't caught in CI. It seems like [snok/install-poetry](https://github.com/snok/install-poetry) is caching the venv.

If this issue crops up again, it might be worth disabling the cache.

It might also be worth running `poetry lock --check` as part of CI, to ensure that the lock file is consistent with pyproject.toml

**Comment by alan-cooney** [comment]
> I was wondering why this wasn't caught in CI. It seems like [snok/install-poetry](https://github.com/snok/install-poetry) is caching the venv, so maybe that's why the yanked dependency wasn't detected.
> 
> If this issue crops up again, it might be worth disabling the cache.
> 
> It might also be worth running `poetry lock --check` as part of CI, to ensure that the lock file is consistent with pyproject.toml
> 
> Let me know if you think either of those are worth doing, and I can raise separate issues!

The second idea seems great - please do add that! We want to keep caching in the CI as it shaves about 5 minutes off the runt time
