### ISSUE TITLE
From_pretrained doesn't save torch.device object correctly in model.cfg.device

### ISSUE THREAD

**Issue by loganriggs** [neelnanda-io/TransformerLens#199]
MVP:
```from transformer_lens import HookedTransformer
import torch as th

device = th.device("cuda:2" if th.cuda.is_available() else "cpu")
model_name = "EleutherAI/pythia-70m-deduped"
model = HookedTransformer.from_pretrained(model_name, device=device)

token = model.to_tokens("hey there").to(model.cfg.device)
model(token)
```
When accessing model.cfg.device, it returns "cuda", and not cuda:2, which causes a "not on same device" error.

A simple fix on my end is setting device to "cuda:2" the string and not the torch.device object.

**Comment by jbloomAus** [comment]
@loganriggs I missed this particular issue when manually checking which related issues were solved by our latest release on GPUs. Are you able to please install from source or the newest release and tell me if this is still an issue? I expect it to be solved.
