### ISSUE TITLE
[Proposal] Support decompose_resid and accumulate_resid having apply_ln parameter

### ISSUE THREAD

**Issue by neelnanda-io** [neelnanda-io/TransformerLens#209]
### Proposal 

ActivationCache.get_full_resid_decomposition has the parameter apply_ln which scales the output (the stacked output of each head and neuron/MLP layer) by the LayerNorm scale factor at the relevant layer (normally the final_ln before the unembed). It'd be useful if other similar functions that return a stack of residual streams did the same, namely `decompose_resid` and `accumulate_resid`, since I often want to use this

**Comment by jbloomAus** [comment]
Solved by PR #220
