### ISSUE TITLE
Verify behaviour of FactoredMatrix __getitem__ with leading dimensions

### ISSUE THREAD

**Issue by rusheb** [neelnanda-io/TransformerLens#224]
Created based on [comment](https://github.com/neelnanda-io/TransformerLens/pull/218/files#r1145470243) on PR #218 

We should have an informative error if the indexing exceeds the leading dimensions which I think was the original intent of the code but may not be working.

ie: if I have [2,3,4,2] * [2,3,2,4] then indexing with more than 2 dimensions (the leading 2,3) shouldn't be possible and an informative error should be raised.

## Acceptance criteria
* Unit test asserting the correct behaviour

**Comment by JayBaileyCS** [comment]
Is this done now thanks to https://github.com/neelnanda-io/TransformerLens/pull/218?

**Comment by jbloomAus** [comment]
@JayBaileyCS  no, this was split out as a separate minor issue.

**Comment by glerzing** [comment]
Hi, I'll start this issue if no one is already on it.
