### ISSUE TITLE
[Proposal] Add a docs pages linking to and explaining the purpose of each demo. 

### ISSUE THREAD

**Issue by jbloomAus** [neelnanda-io/TransformerLens#236]
### Proposal 

We know have a bunch demos and it would be good to have them documented in an index which could be added to the sphinxdoc/readme. 

### Motivation

- Make content easier to access.
- Onboard contributors more easily.

### Pitch

- No point having docs if people can't find them. 
- Current "tutorials" page is kind of sad. Having a "demos/tutorials" page with a section of internal content and external resources would be good. 

<img width="1168" alt="Screenshot 2023-04-08 at 5 35 45 pm" src="https://user-images.githubusercontent.com/69127271/230709628-0d4df58d-6fe1-4e1b-b3fc-031a3d665e6b.png">

### Alternatives

A clear and concise description of any alternative solutions or features you've considered, if any.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

**Comment by JayBaileyCS** [comment]
Forgot to link in PR but this issue is here: https://github.com/neelnanda-io/TransformerLens/pull/263

**Comment by JayBaileyCS** [comment]
This can now be resolved.
