### ISSUE TITLE
[Proposal] Make a logo for Transformer Lens (done), now put the logo in various places

### ISSUE THREAD

**Issue by jbloomAus** [neelnanda-io/TransformerLens#237]
### Proposal 

'nuf said. 

### Motivation

It would be nice to have something for the python index and for the docs. 

I would love for someone to:

- [x] Come up with some ideas
- [x] Share them with the community

This is not a commitment to use any particular outcome only that it seems like a fun task someone might want to do. 

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

**Comment by neelnanda-io** [comment]
My submission
https://watermark-4.creator-spring.com/listing/shoggoth-interp-r-b?product=794

**Comment by neelnanda-io** [comment]
https://labs.openai.com/s/IEqAKVlgRFaBiehretIQD5qlPrompting Dall-E with
prompts like `A scientist using a magnifying glass to look into the head of
Optimus Prime. Film poster, dramatic, artistic` has been fun. My favourites

https://labs.openai.com/s/MZ11J7Khu5k8dmYhn9B4WhZ0
https://labs.openai.com/s/JEygOw0ddNvNe8dA2Na36yVA
https://labs.openai.com/s/A0C014aPvuYzEZihFbfcSQHe
https://labs.openai.com/s/rvtZzrryZH0LGuAMANCc5vly
https://labs.openai.com/s/yJY4fhfX2VbKQfx21pa0a7Cu

**Comment by luciaquirke** [comment]
![image](https://user-images.githubusercontent.com/51809771/232200507-78232625-a364-468a-a871-bd96131b975b.png)
My submission: aesthetic and vaguely evocative of a lens

**Comment by neelnanda-io** [comment]
Ooh, I like it! Nice work Lucia

**Comment by jbloomAus** [comment]
@luciaquirke looks great! @neelnanda-io  Dall-E is also great! I used it for my DTI log. 

Ultimately I feel this decision is up to you Neel, I think Lucia's might work well since:
-  it will probably look really good as an icon which is nice property of a logo. One thing that might be good is having a dark/light versions of it (such as for the docs). This can be as simple as having a version with a border in-casing the logo for when it's on a light background. 
- It does feel evocative as a lens (which appears to be a motif these days eg: tunedLens)
- The light - spectrum also feel reminiscent of the LightCone (and I want our lightcone to go well)

**Comment by luciaquirke** [comment]
I cooked up some variations on the round rainbow-y theme [here](https://docs.google.com/document/d/1iIVkNtLLEJixkbRkt7jsqQg46iQjdUY3NQ46VeNpbaM/edit), e.g.

<img width="296" alt="image" src="https://user-images.githubusercontent.com/51809771/232298478-9f121322-b0b5-4961-a7be-b178b3393b1c.png">

**Comment by neelnanda-io** [comment]
Ooh, I also love the new designs! My favourite is the final one in the doc, for being pretty and clearly lens like

<img width="269" alt="image" src="https://user-images.githubusercontent.com/77788841/232346038-e40deada-10c0-4ff8-8317-acb0163c68dd.png">

My second favourite was the original picture, and my third is the one you pasted above.

**Comment by neelnanda-io** [comment]
How did you make them?

**Comment by callummcdougall** [comment]
I'll throw in 2 submissions, which are covers for some of the TL stuff in the ARENA curriculum. Probably biggest problem as potential logos is that they're not as minimalist as the others in this thread

<img src="https://user-images.githubusercontent.com/45238458/232777726-02e818fc-4215-4ee9-8ea3-e86c477e85f8.png" height="300">
<img src="https://user-images.githubusercontent.com/45238458/232777734-51ef6f79-c785-4040-929d-34c1426e47a5.png" height="300">

**Comment by luciaquirke** [comment]
@neelnanda-io the original one is cribbed from google image search (probably fine for open source?), all the others are from Midjourney using prompts like `glass optical lens with one concave surface, refracting light beams, opaque muted pastel rainbow light, retro, scientific`, `thin outline of a circle on a white background, the outline has an opaque muted pastel rainbow gradient, retro, scientific`

**Comment by neelnanda-io** [comment]
I'm going to use my dictatorial powers and assert that this is our logo - so pretty!

![image](https://user-images.githubusercontent.com/77788841/233735510-47166a9c-1445-4405-8fb5-40cab446304d.png)

**Comment by jbloomAus** [comment]
Fantastic, the tasks now are:

- [ ]  Add the logo to the sphinx docs (https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html)
- [ ] Add the logo to the readme
- [ ] Create and .ico variation of it and add it to the sphinx docs
- [ ] Ensure the logo looks good in various places (ie: if you do the card, do you think it looks good)
- [ ] place some screenshots here to show what it'll look like in the PR.
