### ISSUE TITLE
[Proposal] 1x Memory usage during loading

### ISSUE THREAD

**Issue by UlisseMini** [neelnanda-io/TransformerLens#252]
### Proposal 

Use a technique similar to [huggingface transformers](https://github.com/huggingface/transformers/pull/13466/) to require 1x  model memory when loading (instead of the [default](https://github.com/pytorch/pytorch/issues/64601) of 2x[^1])

### Motivation

I'm trying to do interpretability on llama-13b (technically [vicuna](https://vicuna.lmsys.org/), a finetuned llama) and ran into problems with memory during loading. In particular, loading the model takes 2x the vram it should (empty model init + state dict)[^1]

![image](https://user-images.githubusercontent.com/26258618/233534222-47bd7311-b710-459a-aeab-9ae5dc7c16f2.png)

### Pitch

I'd like the model to be loaded to the GPU without 2x memory usage. This would enable new uses, like loading llama in Google Colab, and enable interpretability on state-of-the-art open RLHF models like [vicuna](https://vicuna.lmsys.org/) and [alpaca](https://crfm.stanford.edu/2023/03/13/alpaca.html). 

### Alternatives

A possible workaround for loading big models would be getting a high ram machine, loading to cpu, then moving it over. For llama-13B this would currently take 26*3 = 78GB of ram in float16[^2]. I find this solution inelegant, and completely blocking some uses, like running in Google Colab. (Or even if high ram Colab works, running bigger models would be blocked.)

Also from reading the code, it seems it'd be tricky to move the model from the CPU to multiple GPUs. Currently the job of moving a `HookedTransformer` to the GPU is done by `HookedTransformer.move_model_modules_to_device`, which uses `model.cfg` to determine `n_devices`. meaning we'd have to
1. Modify `model.cfg['n_devices']`
2. Use `HookedTransformer.move_model_modules_to_device(model, 'cuda')`.

Not that hard, but feels hacky, and I'm not sure these interfaces are meant to be used externally.

### Additional context

Pytorch by default has this 2x memory usage problem ([link](https://github.com/pytorch/pytorch/issues/64601)). Huggingface transformers has a hacky fix [here](https://github.com/huggingface/transformers/pull/13466/) which we could copy for TransformerLens.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

[^1]: Technically 3x because `hf_model` + empty initialized model + state dict, but this issue is only addressing the latter two, which are more annoying since both the empty model and state dict are loaded to the GPU.
[^2]: Another issue... Transformerlens doesn't support mixed precision yet. See [this issue](https://github.com/neelnanda-io/TransformerLens/issues/104). Without fixing this it would take significantly more memory. I get a `RuntimeError: "baddbmm_with_gemm" not implemented for 'Half'` error when trying to load a 16bit model into TL.

**Comment by jmsdao** [comment]
I ran into this when I was trying to run LLaMA-7B on Colab (should be around 14GB VRAM using float16). Since Colab's T4s have ~16GB VRAM, this didn't work using the vanilla `from_pretrained` way for reasons you stated.

Thankfully Huggingface has a package for stuff like this: https://huggingface.co/docs/accelerate/usage_guides/big_modeling

It let's you distribute weights across GPUs and even CPUs/disk, and doesn't have the problem of two copies (random weights + state_dict weights).

Here's the code snippet I used to load LLaMA-7B on Colab:

```python
import torch
from transformers import LlamaForCausalLM
from accelerate import init_empty_weights, load_checkpoint_and_dispatch
from huggingface_hub import snapshot_download

checkpoint_location = snapshot_download("decapoda-research/llama-7b-hf")

with init_empty_weights():  # Takes up near zero memory
    model = LlamaForCausalLM.from_pretrained(checkpoint_location)

model = load_checkpoint_and_dispatch(
    model,
    checkpoint_location,
    device_map="auto",
    dtype=torch.float16,
    no_split_module_classes=["LlamaDecoderLayer"],
)
```

**Comment by jbloomAus** [comment]
@jmsdao that's brilliant! you're a legend!

@UlisseMini This is a reasonable thing to do. 

Prioritise ATM are maintain existing code + stability + enable reasonable contributions by people willing to do the effort followed by adding models for "feature completeness". We also want to have some level or readability/adaptability which trades off strongly with working hard to scale. The other thing is that we want to backchain from valuable research which itself is hard to quantify. So if you're doing something and it's really awesome and there's no way you can do without making a major upgrade that benefits everyone and you couldn't do it on your own, talk to us about it. 

That being said, any and all feedback is generally valued. I'm doing my best to keep mental track of the landscape.

**Comment by jbloomAus** [comment]
@UlisseMini Can you please verify if this works for you? If so I will close this ticket. 

Then either @UlisseMini  or @jmsdao can you please write up a tutorial for working with large models? Maybe cover renting gpus, why you would work with each model, how to get the weights, how you do your analyses/store results etc. Something rough is fine.

**Comment by neelnanda-io** [comment]
Does the PyTorch meta device handle this? Not sure if that's available in
our version, but I think this is the kind of problem it's intended for,
maybe

I broadly feel like loading in CPU only is a fine solution for now, though
James' hack looked potentially Great. I'd be interested in brainstorming
whether we should try to make snippets like that more accessible, eg having
a snippets file or a mini demo.

**Comment by UlisseMini** [comment]
Apologies for not responding. I don't see how to map that code sample to using transformerlens, maybe `init_empty_weights` magically works for transformerlens as well? Haven't tested yet, I'm using the CPU-with-absurd-amounts-of-memory workaround for now.

**Comment by UlisseMini** [comment]
My current solution is reimplementing [our stuff](https://www.lesswrong.com/posts/5spBue2z2tw4JuDCx/steering-gpt-2-xl-by-adding-an-activation-vector) with pure huggingface transformers. This works fine since we don't use many TransformerLens features, ~3 helper functions replaced all the functionality I needed. Pytorch hooks are surprisingly not that cursed.
```python
@contextmanager
def pre_hooks(hooks: Hooks):
    try:
        handles = [mod.register_forward_pre_hook(hook) for mod, hook in hooks]
        yield handles
    finally:
        for handle in handles:
            handle.remove()


# Get ModuleList from arbitrary transformer model
# (Alternatively, we could pick the module list containing >50% of model params.)
def get_blocks(model):
    if isinstance(model, LlamaForCausalLM):
        return model.model.layers
    elif isinstance(model, GPT2LMHeadModel):
        return model.transformer.h
    else:
        raise ValueError(f"Unsupported model type: {type(model)}")

@contextmanager
def residual_stream(model: LlamaForCausalLM, layers: Optional[List[int]] = None):
    "Context manager to track residual stream activations in the model."
    # Plausibly could be replaced by "output_hidden_states=True" in model call.

    stream = [None] * len(get_blocks(model))
    layers = layers or range(len(stream))
    def _make_hook(i):
        def _hook(_, inputs):
            # concat along the sequence dimension
            stream[i] = inputs[0] if stream[i] is None else t.cat([stream[i], inputs[0]], dim=1)
        return _hook

    hooks = [(layer, _make_hook(i)) for i, layer in enumerate(get_blocks(model)) if i in layers]
    with pre_hooks(hooks):
        yield stream
```

**Comment by jbloomAus** [comment]
@UlisseMini It seems to me like James' method should work for you, but that we should implement it under the hood since it's simpler than the current code. I'll get someone on this and we'll update t-lens so this isn't an issue in the future.

**Comment by jbloomAus** [comment]
@UlisseMini  you were right, that was only 3x to 2x. I misunderstood the issue. @slavachalnev  and I have since discussed this at length and he's worked out a fix. Feel free to retry this. I'm going to close this issue though.
