### ISSUE TITLE
[Proposal] Implement SVD Decomposition of OV Circuits, Win, Wout

### ISSUE THREAD

**Issue by jbloomAus** [neelnanda-io/TransformerLens#256]
### Proposal 

This post (https://www.lesswrong.com/posts/mkbGjzxD8d8XqKHzA/the-singular-value-decompositions-of-transformer-weight#The_consistency_check_prompt_was_) introduces some cool methods for identifying tokens associated with the SVD decomposition of OV circuit heads. It would be cool to implement something like this in transformerlens as a utility.

### Motivation

Goes well with attention head detectors added recently. Cool results:

![image](https://user-images.githubusercontent.com/69127271/234188894-fce4c098-d2c3-4b59-a30e-2586b5111830.png)

### Pitch

Make it easier for people to notice semantic concepts being read from and added to the residual stream. 

### Alternatives

Lots of non-linear stuff happening in models too which we can't model. Would love something that measured that. 

### Additional context

Code example from post: https://colab.research.google.com/drive/1G5e5I6zEKZUkuV6DR3yZEhiCoWCTLQdh?usp=sharing

### Checklist

- [x] I have checked that there is no similar [issue]() in the repo (**required**)

**Comment by JayBaileyCS** [comment]
I am now working on this.

**Comment by JayBaileyCS** [comment]
This was much more of a pain than I expected, because I kept running into numerical instability problems...but it turns out that's just how linear dependence works. A PR https://github.com/neelnanda-io/TransformerLens/pull/285 is now up for this. Thanks for the patience.
