### ISSUE TITLE
[Proposal] Update GitHub CI to run in ubuntu GPU enable environment

### ISSUE THREAD

**Issue by bryce13950** [neelnanda-io/TransformerLens#265]
### Proposal 

GPU CI runners appear to currently be in private beta. Once this issue https://github.com/github/roadmap/issues/505 is closed, we can update our GitHub actions to run against the new ubuntu runners.

### Motivation

This will allow all of our tests to utilize full GPU capabilities, and it will greatly improve our testing capabilities, especially in the demos, which will now be able to run more efficiently and more accurately. 

### Pitch

We will need to change the GitHub actions config, and at that point any tests that are being manually directed to the CPU can be run on cuda. 

### Alternatives

For the time being, we can leave as is.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

**Comment by alan-cooney** [comment]
FYI Mac M1 runners are now publicly available, and these are sufficiently powerful to run most tests (Ubuntu GPU is still not in public beta). However they are quite expensive, so would need approval from Neel if we want to move tests to this.

**Comment by neelnanda-io** [comment]
How expensive?

**Comment by alan-cooney** [comment]
They're $0.16/minute which at last weeks use, and assuming good caching plus only running the tests that need it, nets out at $150/month (3x/day * 10 minutes * 365/12 * 0.16). This would increase as the repo popularity increases.

**Comment by bryce13950** [comment]
It's probably better to wait for ubuntu runners. We don't really need the CI to run on GPU yet. It would be nice, but probably not necessary. It seems to me that there is probably a bit of an added fee for it being Apple hardware. M series Macs are also at the present time not cuda compatible to my knowledge, so the advantage of using a M1 runner would probably be negligible. I think the introduction of M series runners is probably meant to be more targeted at CIs for iOS/macOS apps.

**Comment by alan-cooney** [comment]
M1 macs have mps which has similar capabilities to CUDA (and is orders of magnitude faster than using the cpu). Closing this issue however until we have a concrete need for GPU testing.
