### ISSUE TITLE
[Bug Report] Tokenization in test_prompt in utils.py sometimes causes IndexError when prompt+answer is tokenized differently together vs separately

### ISSUE THREAD

**Issue by jknowak** [neelnanda-io/TransformerLens#271]
in utils.py, function test_prompt the whole prompt+answer string is tokenized, then we get the tokens in string form from each part separately
```
tokens = model.to_tokens(prompt + answer, prepend_bos=prepend_bos)
prompt_str_tokens = model.to_str_tokens(prompt, prepend_bos=prepend_bos)
answer_str_tokens = model.to_str_tokens(answer, prepend_bos=False)
```
the issue is, later in the code we get lengths of the latter two
```
prompt_length = len(prompt_str_tokens)
answer_length = len(answer_str_tokens)
```
and these lengths are used to index over the `tokens` tensor:
```
for index in range(prompt_length, prompt_length + answer_length):
        answer_token = tokens[0, index]
```

so if prompt_length+answer_length happens to be longer, because the model tokenized them differently than it would the whole prompt+answer string, especially when we set `prepend_space_to_answer` to `False`, we get `IndexError`
e.g.
```
 IndexError: index 15 is out of bounds for dimension 1 with size 15
```

**Comment by jknowak** [comment]
When I'll have more time I can check what approach would be better:
- indexing using the length of `tokens`
- tokenizing the sum of `prompt_str_tokens` and `answer_str_tokens` (feels weird)

**Comment by jbloomAus** [comment]
@jknowak thanks for finding this!

I'd love you/a contributor to make a PR that:
- [ ] Makes a failing test demonstrating this issue and expecting correct behavior.  (one commit)
- [ ] Make a commit fixing the issue/making the test pass (one commit)
- [ ] Explore whether there are any similar issues around this and if so fixing/documenting them.

If you have questions, can discuss more here. Existing tests should provide examples of the style we expect and I'll give feedback if needed.
