### ISSUE TITLE
matplot lib not in the pyproject.toml file

### ISSUE THREAD

**Issue by erlebach** [neelnanda-io/TransformerLens#279]
I am trying out `main_demo.ipynb`, and everything was working until I reached the line
``` 
%matplotlib
```
which generated an error since matplotlib was never included into the framework. Surely you must have tested this, so I do not understand how the code can work without matplotlib. The imshow routines that follow also do not work as a consequence. Thank you.

**Comment by neelnanda-io** [comment]
Wild. That notebook should not use matplotlib, so if you delete that line
everything will work, no clue how it got there. I would love a PR deleting
that line! You may need to install Plotly if your system doesn't have that
already. The tutorials are designed to work in Google Colab alas, and have
some dependencies that we don't want to make dependencies of the main
library (Colab has a bunch of stuff pre installed). But matplotlib is not
one of them!

**Comment by erlebach** [comment]
Thank you, Neel. Love your work!

**Comment by jbloomAus** [comment]
@bryce13950 confirming you fixed this in the current demo PR.

**Comment by bryce13950** [comment]
Yep! This can be either closed, or marked to be closed when my PR gets merged

**Comment by bryce13950** [comment]
@erlebach if you want to look at this demo in a working state, it should be running fine here https://github.com/Lingwave/TransformerLens/blob/tests-regression/demos/Main_Demo.ipynb
