### ISSUE TITLE
[Question] Is there a reason `HookedTransformer` doesn't have a `device` attribute or method?

### ISSUE THREAD

**Issue by albertsgarde** [neelnanda-io/TransformerLens#287]
### Question

`HookedTransformer` has both a `cuda`, a `cpu` and a `to` method to move the model to various devices, but no method to figure out which device it is currently on.
This would be very useful in order to ensure that new tensors I create are on the same device without having to move the model first.
I know I could just get the device of one of the tensors in the model, but a general model device method seems more principled

It could be that the method doesn't exist because "what device the `HookedTransformer` is on" is not well-defined, maybe because it can be split across multiple devices.
Is this the case or is there another reason?

**Comment by jbloomAus** [comment]
Config should have a device attribute I think. And an n_devices attribute.

**Comment by slavachalnev** [comment]
Yeah, it can be split over multiple devices. Also see https://stackoverflow.com/questions/58926054/how-to-get-the-device-type-of-a-pytorch-module-conveniently
