### ISSUE TITLE
[Proposal] Adapt Loading From Pretrained to give a custom cache dir for the HuggingFace model

### ISSUE THREAD

**Issue by neelnanda-io** [neelnanda-io/TransformerLens#288]
### Proposal 

loading_from_pretrained.py, under the hood, uses HuggingFace's AutoModelForCausalLM.from_pretrained. This caches the model weights loaded, to a folder indicated by `cache_dir`, but it can be hard to expose and edit the folder cached to so it goes to the default folder. This is sometimes annoying (in my case, I haev a 20GB disk with a 1000GB persistent volume attached and I want to cache to the persistent volume). It might also be nice to turn off caching altogether. 

A possible solution would be adding a cache_dir param to `HookedTransformer.from_pretrained` or adding the option to pass in any dict of arguments to the underlying HuggingFace loader, to allow future such use cases.

**Comment by glerzing** [comment]
Hi Neel, if nobody else is on it I will take this issue.
