### ISSUE TITLE
[Proposal] Implement TinyStories

### ISSUE THREAD

**Issue by MatthewBaggins** [neelnanda-io/TransformerLens#289]
### Proposal 

Implement models from the paper [TinyStories: How Small Can Language Models Be and Still Speak Coherent English?](https://arxiv.org/abs/2305.07759). See also this [LW post](https://www.lesswrong.com/posts/dMoaBvcxpBE7LcES4/tinystories-small-language-models-that-still-speak-coherent).

### Motivation

These models appear to be much more capable/coherent in their outputs, relative to commonly used GPTs of similar sizes, as well as [more interpretability-friendly](https://www.lesswrong.com/posts/dMoaBvcxpBE7LcES4/tinystories-small-language-models-that-still-speak-coherent#Interpretability).

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/neelnanda-io/transformerlens/issues) in the repo (**required**)

**Comment by Felhof** [comment]
l looked into this a bit and it seems that this should be fairly quick since similar architectures are already implemented. I will make sure that the models work as expected and create a PR sometime tomorrow.
