### ISSUE TITLE
[Proposal] Give ActivationCache a method to stack activations across the layer dimension

### ISSUE THREAD

**Issue by neelnanda-io** [neelnanda-io/TransformerLens#300]
### Proposal 

I often want to get access to eg all `mlp_post` activations across all layers. ActivationCache should have a method that takes in the name of the hook, maybe the name of the sublayer, and returns the stack of activations (with an additional layer dimension as the first axis)

**Comment by jbloomAus** [comment]
added 4 months ago by Neel
