### ISSUE TITLE
[Proposal] Add a HookPoint that can edit the input to an MLP

### ISSUE THREAD

**Issue by ArthurConmy** [neelnanda-io/TransformerLens#309]
### <b>Proposal

Add a HookPoint that can edit the input to an MLP (and not to the general residual stream).</b>

### Motivation

Let's say I want to zero out the output of one attention head into one future MLP.

Then there is no clean way to do this as far as I can tell. 

https://github.com/neelnanda-io/TransformerLens/blob/c268a7159a6f8d5c78236a3f958f2d704fbc940f/transformer_lens/components.py#L926-L933

Editing `hook_resid_mid` edits the residual stream beyond the MLP too

### Pitch

Either 

i) Edit 

https://github.com/neelnanda-io/TransformerLens/blob/c268a7159a6f8d5c78236a3f958f2d704fbc940f/transformer_lens/components.py#L934-L936

so `resid_post` is computed by `resid_pre + attn_out + mlp_out` so that `hook_resid_mid` can be used for my the purpose of the motivation.

OR

ii) Turn `normalized_resid_mid = self.ln2(resid_mid)` into `normalized_resid_mid = self.ln2(self.hook_mlp_in(resid_mid))` and add the `hook_mlp_in` HookPoint if and only if we give a special flag to the model

I'm super curious if solution i) is OK (it's a lot faster for me to code!). We could call the config option for option to i) `HookedTransformerConfig.decouple_hook_resid_mid` (defaults to `False`)

**Comment by jbloomAus** [comment]
Definitely ii. 

It's hard to assess whether/how many people rely on the current interpretation of the hook and so the downside risk from this change is high. Thus ii is preferable. 

Why only add it if we give a special flag to the model? Seems like it should be fine not to?

**Comment by ArthurConmy** [comment]
Actually, I just checked that since they both use the same underlying storage, there is no memory bloat, so I'll go ahead and implement this by default.

**Comment by ArthurConmy** [comment]
https://github.com/neelnanda-io/TransformerLens/pull/313 Reopening based on Neel’s comment . I can implement this
