### ISSUE TITLE
[Proposal] Reduce the code documentation complexity by declaring internal functions with a leading "_"

### ISSUE THREAD

**Issue by glerzing** [neelnanda-io/TransformerLens#310]
### Proposal and motivation

The [code documentation](https://neelnanda-io.github.io/TransformerLens/transformer_lens.html) is pretty big. But some functions are not meant to be called by end users. Adding a "_" in front of functions or methods (e.g. `make_model_alias_map` => `_make_model_alias_map`) causes it not to be displayed on Sphinx. This would reduce the quantity of superfluous information in the documentation (in particular in `loading_from_pretrained.py`), but may slightly break backward compatibility if any end user was actually using one of those functions directly (for demos it's easy to verify). If you think this is useful, I can make the modifications, if you think this is not, don't hesitate to close this issue.

**Comment by ArthurConmy** [comment]
I like the idea of reducing the docs.

However, I think that renaming file names is a bad idea because this can break backwards compatibility.

I would happily review changes that add 

```
autodoc_default_options = {
    'exclude-members': 'make_model_alias_map, my_func_2' # and more undocumented things
}
```

to the `conf.py` and show that this works
