### ISSUE TITLE
[Proposal] Automatically regenerate the docs on push to main

### ISSUE THREAD

**Issue by ArthurConmy** [neelnanda-io/TransformerLens#314]
### Proposal
Automatically regenerate the docs on push to main.

### Motivation
The committed `.rst` files are sometimes out of date if not explicitly regenerated in a PR, as running `sphinx-apidoc` locally showed differences [on a recent PR](https://github.com/neelnanda-io/TransformerLens/pull/312).

There are inconsistencies in the documentation that is being served through GH Docs and the actual state of the repository. Recently the "torchtyping helper module" was in the documentation, but the module had been removed from the repository. It is proposed to add automatic rst generation in the CI pipeline to keep the documentation up-to-date.

### Pitch
The proposed solution is to add automatic `rst` generation in the CI pipeline. 
This can be accomplished by adding a step in the GH action that runs `sphinx-apidoc` whenever changes are pushed to the repository (I think! CC @dkamm @Aprillion ) 
This will ensure that the documentation stays consistent with the state of the repository.

### Checklist
[x] I have checked that there is no similar [issue](https://github.com/neelnanda-io/transformerlens/issues) in the repo (required)

**Comment by alan-cooney** [comment]
Fixed in #398
