### ISSUE TITLE
[Bug Report] `refactor_factored_attn_matrices` uses lots of GPU memory

### ISSUE THREAD

**Issue by ArthurConmy** [neelnanda-io/TransformerLens#329]
**Describe the bug**
When loading models with `refactor_factored_attn_matrices=True` and `device="cuda"`, they take up a lot of space on GPU. Thanks to @callummcdougall for noticing this. See example code at bottom for snippets and statistics.

**System Info**
vast.ai 2*3090 devbox, on branch main.

**Additional context**
Doing `import gc; gc.collect(); import torch; torch.cuda.empty_cache()` after the refactor stuff would help but if someone could look into further whether we can keep the permanent refactor objects on GPU (or not) that would be great and save some more trouble! If nothing else I can add a warning if we enter the refactor function with device equal to GPU.

### Checklist

- [ :white_check_mark:  ] I have checked that there is no similar [issue](https://github.com/neelnanda-io/TransformerLens/issues) in the repo (**required**)

Example code

On my machine with 3090s, this uses 46% of GPU memory:

```
model = HookedTransformer.from_pretrained(
    "solu-10l", # "NeelNanda/SoLU_10L1280W_C4_Code"
    device="cuda",    
    refactor_factored_attn_matrices=True,
)
```

I check memory with 

```
_r = torch.cuda.memory_reserved(0)
_a = torch.cuda.memory_allocated(0)
_p = 100*(_r-_a)/_r 
print(f"Percentage of reserved memory that is allocated: {_p:.2f}%")
```

After `import gc; gc.collect(); import torch; torch.cuda.empty_cache()` this is down to 6%

However, with this code

```
model = HookedTransformer.from_pretrained(
    "solu-10l", # "NeelNanda/SoLU_10L1280W_C4_Code"
    device="cpu",
    refactor_factored_attn_matrices=True,
)
model.to("cuda")
```

just 0.16% of my memory is used

**Comment by Felhof** [comment]
Is `refactor_factored_attn_matrices` really the issue here? As far as I can tell, using `from_pretrained` to load models to the GPU directly always takes up much more GPU memory than first loading them to the CPU and then moving them to the GPU. When I use your snippet, setting `refactor_factored_attn_matrices=True` only increases the total memory usage by a small amount.
