### ISSUE TITLE
[Bug Report] from_pretrained() directory conflict issue

### ISSUE THREAD

**Issue by hijohnnylin** [neelnanda-io/TransformerLens#332]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
HookedTransformer.from_pretrained() fails if user's home dir already contains directory with same name as model. For example, trying to download gpt2-xl when your home directory already has a directory named gpt2-xl.
I'm on macOS.

**Code example**
Simple to reproduce. Just create an empty directory called "gpt2-xl" in your Mac's home directory. Then try running:
`model = HookedTransformer.from_pretrained("gpt2-xl", device=device)`

It will fail with the following error:
```
  File "/Users/[MYUSERNAME]/.pyenv/versions/3.10.0/lib/python3.10/site-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: gpt2-xl does not appear to have a file named config.json. Checkout 'https://huggingface.co/gpt2-xl/None' for available files.
```

**System Info**
Describe the characteristic of your environment:
 * pip installation
 * macOS
 * Python 3.10

**Additional context**
Cause: It looks like it's checking to see if "gpt2-xl" is a directory in the home dir - and if it is, then it checks for "config.json" in that directory. It can't find that file, so it raises the error above.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/neelnanda-io/TransformerLens/issues) in the repo (**required**)

**Comment by glerzing** [comment]
The implementation of `from_pretrained` is based on Hugging Face's transformers library. And it's also the case with the transformers library. I think it's done on purpose and is probably not an issue.
But it's surprising that when adding the argument `force_download=True`, the error still occurs. That might be worth an issue in Hugging Face's transformers library, even though but I doubt they'll take the risk of modifying the behavior of `from_pretrained`. But I personally don't think there is anything to modify in TransformerLens.

**Comment by hijohnnylin** [comment]
Ah interesting, thanks. Can you explain more on why this is done on purpose? As in, why isn't it creating and using a new unique subdirectory for these temporary checks, instead of using the user's home directory? I believe it all eventually ends up in `~/.cache/huggingface/hub` anyway.

**Comment by glerzing** [comment]
TransformerLens uses Hugging Face's function `hf_hub_download`, which checks first if it is already present locally in a folder before checking the cache or downloading.
As I understand it, your Python interpreter is executed from your home directory (you can check it with `import os;os.getcwd()`, or perhaps your home directory is in the path : `import sys;sys.path`), and there is a directory `gpt2-xl` inside, so `hf_hub_download` considers that the model is there. But there is no config file inside this directory.
