### ISSUE TITLE
[Bug Report] names_filter not fulfilling expected functionality in v1.3.0

### ISSUE THREAD

**Issue by 123epsilon** [neelnanda-io/TransformerLens#340]
**Describe the bug**
Using the `names_filter` parameter in the `run_with_cache` function for HookedTransformer does not behave as expected.

**Code example**
The parameter should accept either a `str`, `list`, or `lambda` - but only the lambda seems to work.

Working:
```
device = "cuda" if torch.cuda.is_available() else "cpu"
gpt2_small = HookedTransformer.from_pretrained("gpt2-small", device=device)
tokens = gpt2_small.to_tokens("Henry is a rotten")
logits, cache = gpt2_small.run_with_cache(tokens, names_filter=lambda name: name == 'blocks.0.attn.hook_z'], remove_batch_dim=True)
print(cache.keys()) # dict_keys(['blocks.0.attn.hook_z'])
```

But the following are not working:

```
device = "cuda" if torch.cuda.is_available() else "cpu"
gpt2_small = HookedTransformer.from_pretrained("gpt2-small", device=device)
tokens = gpt2_small.to_tokens("Henry is a rotten")
logits, cache = gpt2_small.run_with_cache(tokens, names_filter='blocks.0.attn.hook_z', remove_batch_dim=True)
print(cache.keys()) # dict_keys([]) <- empty?
```

The following throws an error:
```
device = "cuda" if torch.cuda.is_available() else "cpu"
gpt2_small = HookedTransformer.from_pretrained("gpt2-small", device=device)
tokens = gpt2_small.to_tokens("Henry is a rotten")
logits, cache = gpt2_small.run_with_cache(tokens, names_filter=['blocks.0.attn.hook_z'], remove_batch_dim=True) # error here
print(cache.keys()) 
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/arhamkhan/miniconda3/envs/attnlens/lib/python3.10/site-packages/transformer_lens/HookedTransformer.py", line 429, in run_with_cache
    out, cache_dict = super().run_with_cache(
  File "/Users/arhamkhan/miniconda3/envs/attnlens/lib/python3.10/site-packages/transformer_lens/hook_points.py", line 447, in run_with_cache
    cache_dict, fwd, bwd = self.get_caching_hooks(
  File "/Users/arhamkhan/miniconda3/envs/attnlens/lib/python3.10/site-packages/transformer_lens/hook_points.py", line 512, in get_caching_hooks
    if names_filter(name):
  File "/Users/arhamkhan/miniconda3/envs/attnlens/lib/python3.10/site-packages/transformer_lens/hook_points.py", line 493, in <lambda>
    names_filter = lambda name: name in names_filter
TypeError: argument of type 'function' is not iterable
```

**System Info**
 
 I am using a pip installation inside a conda environment on MacOS Ventura 13.0
`python==3.10.12`
`transformer-lens==1.3.0`

Notably on another machine where I am using `transformer-lens @ git+https://github.com/neelnanda-io/TransformerLens.git@347e65235140d942301452a55505c9215b36806a` does not experience this issue - not that this is necessarily the latest commit for which this is true.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/neelnanda-io/TransformerLens/issues) in the repo (**required**)

**Comment by ArthurConmy** [comment]
Glad I wasn't the only one who experienced this! This has been flagged and fixed [here](https://github.com/neelnanda-io/TransformerLens/pull/321). You can build from source (as you did with the pip install that uses the commit hash) and we will have a new release out soon which will fix this since we've already pushed the fix to main

**Comment by 123epsilon** [comment]
@ArthurConmy Thanks!

**Comment by ArthurConmy** [comment]
@123epsilon the new release https://github.com/neelnanda-io/TransformerLens/releases/tag/v1.4.0 should fix this

**Comment by 123epsilon** [comment]
@ArthurConmy Thank you!
