### ISSUE TITLE
[Proposal] Scalar Multiplication * for FactoredMatrix

### ISSUE THREAD

**Issue by matthiasdellago** [neelnanda-io/TransformerLens#348]
Is there any particular reason why multiplication with a scalar (*) should not be implemented for FactoredMatrix?
I need it in my research, and while there are easy workarounds I would like to add it to streamline working with FactoredMatrix.
In the absence of counterarguments I would implement it and the according tests myself and submit a PR.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/neelnanda-io/transformerlens/issues) in the repo (**required**)

**Comment by neelnanda-io** [comment]
Go for it
