### ISSUE TITLE
[Question] Does TransformerLens support running with some specified intervention?

### ISSUE THREAD

**Issue by adamyedidia** [neelnanda-io/TransformerLens#362]
### Question

Does TransformerLens currently support running a model on a prompt but with some intervention, e.g. getting the result when adding a specified vector at at a given part of the network? If not, would that be a useful thing for me to add?

**Comment by ArthurConmy** [comment]
Are you familiar with the "Hooks: intervening on activations" part of the main demo https://colab.research.google.com/github/neelnanda-io/TransformerLens/blob/main/demos/Main_Demo.ipynb#scrollTo=1-WVEbsrhGDS ?
