### ISSUE TITLE
[Proposal] Remove lru_caching from HookedTransformer weight methods

### ISSUE THREAD

**Issue by ArthurConmy** [neelnanda-io/TransformerLens#363]
### Proposal 

Remove `@lru_cache` decorator from HookedTransformer

### Motivation

Caching this call has irritating effects 

```python
#%% 

import transformer_lens.HookedTransformer as HT

#%%

gpt2 = HT.from_pretrained("gpt2").cuda()

#%%

print(gpt2.W_K.shape) # do an initial call of W_K

#%%

gpt2.to("cpu")

#%%

print(gpt2.W_K.device) # cuda!
```

I don't think the upsides of caching (for low mem usage) outweigh the downsides, as it doesn't appear that repeated calls to `W_K` are made anywhere in the repo. I'll implement the ~3 line PR making these changes if someone thinks this is a good idea. If you think this is a bad idea, please say too!

**Comment by neelnanda-io** [comment]
My main concern here would be that it's not performant to repeatedly stack the weights rather than caching. On the other hand, it's plausible this is trivial, and not worth the pain. Anyone tried measuring it on a large-ish model?

**Comment by ArthurConmy** [comment]
```python
model = transformer_lens.HookedTransformer.from_pretrained("pythia-2.8B")
t0 = time.time()
for layer in range(model.cfg.n_layers):
    for head in range(model.cfg.n_layers):
        w_k = model.W_K[layer, head]
        w_k.norm() # some random calculation
print(time.time() - t0)
```

takes 0.03 seconds on main and 1.28 seconds with this change.

I think the change is still worth it because if someone wants frequent `W_K` access they can just call declare `my_W_K = model.W_K` to get around this slight slowness

**Comment by neelnanda-io** [comment]
Cool, so that's about 1ms per stack on a 3B model. Yeah, this seems
trivial, I'd be happy for you to remove the caching lines.
