### ISSUE TITLE
[Question] RuntimeError: Expected all tensors to be on the same device, Loading Llama from pretrained

### ISSUE THREAD

**Issue by SophieLiao0109** [neelnanda-io/TransformerLens#371]
Hi, there,

I wish to load huggingface Llama2 model weights and then distribute it to HookedTransformer. Here is my code,
`device = "cuda" if torch.cuda.is_available() else "cpu"`
 `n_devices = torch.cuda.device_count()`
 `print("Using {} devices.".format(n_devices))`
  `hf_model = LlamaForCausalLM.from_pretrained("meta-llama/Llama-2-7b-hf", device_map='auto', cache_dir="xxx/xxx/xxx", local_files_only=True)`
  `model = HookedTransformer.from_pretrained("Llama-2-7b", hf_model=hf_model,
            fold_ln=False, center_writing_weights=False, 
            center_unembed=False, n_devices=n_devices)`
  `tokenizer = LlamaTokenizerFast.from_pretrained("huggyllama/llama-7b", padding_side='right', cache_dir="xxx/xxx/xxx")`.

I have been trying to load the model using multiple GPUs, however, I always run into this problem:
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking 
argument for argument mat2 in method wrapper_CUDA_bmm)`

Does anyone why this issue has occurred? Any help would be appreciated. The transformerlen version I have been using is 0.0.0
Edit: the same issue occurs for transformerlen version: 1.5.0

**Comment by SophieLiao0109** [comment]
Not sure if this is a common problem. But in my case, some parameters are not sent to `cuda` during `load_state_dict`. The problem comes from this line [https://github.com/neelnanda-io/TransformerLens/blob/main/transformer_lens/HookedTransformer.py#L1264](url). The way I have solved this is by explicitly setting `b_V = state_dict[f"blocks.{layer}.attn.b_V"].cuda()`. Hopefully, this can help if anyone encounters the same issue as me

**Comment by artkpv** [comment]
I see the same issue. It looks like LLAMA2 7B loads itself partially into CPU though the code explicitly demands CUDA. I tried to convert to CUDA inside `.from_pretrained` in TransformerLens as @SophieLiao0109 did but I got CUDA out of memory. I have 16 GB VRAM. The HF models loads:

```
hf_model = LlamaForCausalLM.from_pretrained(
    "meta-llama/Llama-2-7b-chat-hf",
    torch_dtype=model_type,
    device_map=device,
    low_cpu_mem_usage=True,
)
hf_model = hf_model.to(device)
```
