### ISSUE TITLE
[Proposal] Support Mistral 7B model

### ISSUE THREAD

**Issue by neelnanda-io** [neelnanda-io/TransformerLens#387]
### Proposal 

Mistral AI have released a 7B model which they claim is better than LLaMA 13B, it'd be nice if TransformerLens supports it. This seems like a good 7B model, and 7B is about the largest model that's easy enough to work with without needing very high end GPUs, so I'd like TL to support the best 7Bs around. Unlike LLaMA it's actually open source under an Apache 2.0 license

The [blog post](https://mistral.ai/news/announcing-mistral-7b/), and [HuggingFace page](https://huggingface.co/docs/transformers/main/model_doc/mistral)

### Details

New architecture that'd need to be supported:
* Grouped Query Attention (which will also unblock LLaMA 2 70B!)
* Sliding Window attention (I believe this may already be supported for GPT-Neo?)
* Their tokenizer (should be easy)

**Comment by Felhof** [comment]
I have started working on this. Sliding window attention is indeed already supported for GPT-Neo, so the main chunk of work will be Grouped Query Attention.

**Comment by neelnanda-io** [comment]
Amazing, thanks for taking this on!
