### ISSUE TITLE
[Proposal] Set GitHub website url

### ISSUE THREAD

**Issue by alan-cooney** [neelnanda-io/TransformerLens#405]
Click the edit wheel on the right of "About" [here](https://github.com/neelnanda-io/TransformerLens/) and add:

https://neelnanda-io.github.io/TransformerLens/

Maybe add a one-liner description as well (e.g. "Mechanistic interpretability library for language models like GPT).

One for Neel I think (I don't have permission to change this).

**Comment by neelnanda-io** [comment]
Thanks, fixed! (For future reference, feel free to slack me about things like this)
