### ISSUE TITLE
[Proposal] Drop Python 3.7/3.8 support

### ISSUE THREAD

**Issue by alan-cooney** [neelnanda-io/TransformerLens#411]
### Proposal 

We previously supported these old versions because Colab was very out of date. This is [no longer the case](https://medium.com/google-colab/colab-updated-to-python-3-10-27eb02daa162#:~:text=We%E2%80%99re%20happy%20to%20announce%20that,10%2C%20it%20brings) and it now defaults to 3.10.

### Motivation

Dropping these old versions would reduce dependency nightmares when adding packages. It will also allow us to use standard Python typing (e.g. `list[]` rather than `from typing import List`) which is needed at some point because the whole Python typing package is deprecated and going to be dropped in 2024/5.

**Comment by alan-cooney** [comment]
@jbloomAus keen to get your thoughts as well

**Comment by alan-cooney** [comment]
To note - if we drop 3.7 we can also require torch >2.0 which opens up compiling/other performance boots

**Comment by alan-cooney** [comment]
Dropping just 3.7 for now - we can think about 3.8 later.

**Comment by neelnanda-io** [comment]
Sounds good to me

**Comment by neelnanda-io** [comment]
Is it likely that there are users who won't want to upgrade who are still using old Python versions? I'm not sure if there's a problem with "just upgrade your Python version" as an answer

**Comment by alan-cooney** [comment]
It's possible some people are still using 3.8 (but 3.7 seems unlikely now).

I've left 3.8 in but we'll probably need to drop it when 3.13 comes out, as 3.13 is expected to drop support for some things we're using (e.g. using `from Typing import List` as they want you to use the generic `list` that came out in 3.9).

**Comment by jbloomAus** [comment]
I'm strongly in favour of dropping support for 3.7/3.8. They're fairly old
at this point.

**Comment by ArthurConmy** [comment]
Two reasons to err on the side of keeping support for all packages: 
1. Some people may be using TransformerLens with other packages that require Python <3.9 (I don't know how common this is)
2. Some crappier GPU services don't give you sudo access, and only have older Python versions. At least one part of the Hofvarpnir AI Safety cluster only has old Python (but @UFO-101 would know how big a deal this is, more than I do)

**Comment by alan-cooney** [comment]
Yep makes sense - I think for now just dropping 3.7 should be fine (which I've done). We can drop 3.8 next year, or workaround if it's a real problem (e.g. with conditional imports).

**Comment by jbloomAus** [comment]
While we're on the topic of not supporting things, I have a hot take: I
know that type checking is very valuable in lots of ways but my take after
seeing how much effort it is to deal with the typing dependencies is that
it's not worth it. If we have decent tests and docs then the shapes of
tensors will be clear/obvious. Moreover, it bloats the code and it's
particularly unreadable in lots of places. Simplifying t-lens so the whole
thing is easier to install/dev/workwith/read seems like a worthwhile goal
imo. I'd suggest we remove beartype (as we start having better tests/docs),
scale back our use of bespoke classes and keep it simple.

**Comment by alan-cooney** [comment]
Maybe create a new issue to discuss this if you're keen to remove them? In general I personally find them very helpful
