### ISSUE TITLE
[Proposal] Support Mixtral

### ISSUE THREAD

**Issue by neelnanda-io** [neelnanda-io/TransformerLens#471]
### Proposal 

Add support for [Mixtral](https://mistral.ai/news/mixtral-of-experts/), Mistral's new 47B parameter mixture of experts model. 

### Motivation

Mixtral seems to plausibly be the current best open source model. More importantly, mixture of experts seems increasingly popular, and it would be great to enable mech interp work on it to understand how it differs from normal models. 

Note that I expect this to be a bit of a pain to implement, and in particular I would recommend just doing the easiest thing, where we basically treat this as a 47B model with fancy MLP layers that involve routing to different weight matrices, without worrying about how to do efficient and scalable inference. I recommend starting by reading the HuggingFace [Mixtral code](https://github.com/huggingface/transformers/blob/v4.36.1/src/transformers/models/mixtral/modeling_mixtral.py#L951) to figure out how it works. Note also that I expect you to need multiple GPUs to get the model working. 

You could use the [LLaMA PRs](https://github.com/neelnanda-io/TransformerLens/pull/234) and [Mistral PRs](https://github.com/neelnanda-io/TransformerLens/pull/443) as models for what this should look like

https://huggingface.co/01-ai/Yi-6B
https://huggingface.co/01-ai/Yi-34B

**Comment by RohitRathore1** [comment]
Is someone working on this? If I take this then should I arrange the required GPUs on my own?

**Comment by neelnanda-io** [comment]
I'm not aware of anyone working on this. If you're interested in taking
this on, that would be great! I'm afraid we can't easily offer support in
getting GPUs, so you'll need to take care of that yourself (I'd recommend a
provider like vast or runpod)

**Comment by catubc** [comment]
Hey all. Any progress on this?  I might be interested in helping.

**Comment by neelnanda-io** [comment]
I'm not aware of any - if you want to take it on, that'd be awesome :)

**Comment by RohitRathore1** [comment]
> Hey all. Any progress on this? I might be interested in helping.

Yes, sorry for the delay. I was not able to arrange GPUs, but now I have access. @catubc if you would love to work together then we can.

**Comment by collingray** [comment]
> > Hey all. Any progress on this? I might be interested in helping.
> 
> Yes, sorry for the delay. I was not able to arrange GPUs, but now I have access. @catubc if you would love to work together then we can.

Hey, I've got an implementation of this mostly working sans some processing features, if you would like something to work off of: [link](https://github.com/collingray/TransformerLens/tree/add-mixtral)

**Comment by catubc** [comment]
Hi @RohitRathore1 , I found a work around for a smaller model for next 2 weeks (am rushing towards a deadline). But I'll circle back to @collingray approach shortly. brb

**Comment by collingray** [comment]
Ok it seems that my implementation is more complete than I remember (although I'm getting very high error on some tokens), so I'm going to put up a pr for it

**Comment by RohitRathore1** [comment]
@collingray Thanks for your PR.
