### ISSUE TITLE
[Question] how to load model from local

### ISSUE THREAD

**Issue by XeeKee** [neelnanda-io/TransformerLens#476]
Thank you very much for your outstanding work. I have a question: if I want to load a model from my local directory, how should I proceed in my code, using 
'HookedTransformer.from_pretrained("gpt2", cache_dir="/Circuit/models/gpt2", local_files_only=True)' 
but it download the model from Hugging Face"

**Comment by ajyl** [comment]
I thiiiiiink one way to do it is as following:

```
hf_model = GPT2ForCausalLM.from_pretrained("/Circuit/models/gpt2")
hooked_model = HookedTransformer.from_pretrained("gpt2", hf_model=hf_model)
```
