### ISSUE TITLE
[Proposal] Add resize_token_embedding functionality

### ISSUE THREAD

**Issue by JackCai1206** [neelnanda-io/TransformerLens#487]
### Proposal 
Add a resize_token_embedding function to HookedTransformer. 

### Motivation

Huggingface models are equipped with a function `model.resize_token_embedding` so the embedding layer can be resized easily after adding special tokens to the tokenizer. I can't find a similar function for the HookedTransformer class. 
I am working with a pretrained GPT2 model and I want to add special tokens to the tokenizer, but resizing the embedding layer is not straightforward. 

### Pitch

Add a function similar to the one described here to the HookedTransformer class. https://huggingface.co/docs/transformers/main_classes/model#transformers.PreTrainedModel.resize_token_embeddings

### Alternatives

I have tried initializing a huggingface PretrainedModel and Pretrained Tokenizer class, add my special tokens, and then using the initlized huggingface model and tokenizer to create HookedTransformer, but it does not work. The code to reproduce the error is the following.

```
hf_model: PreTrainedModel = AutoModelForCausalLM.from_pretrained(init_from)
    hf_tokenizer: PreTrainedTokenizer = AutoTokenizer.from_pretrained(init_from)
    hf_tokenizer.add_special_tokens({
        'pad_token': '<#>',
        'additional_special_tokens': ['<1>', '<2>', '<3>', '<4>', '<5>', '<6>', '<7>', '<8>', '<9>', '<0>', '<+>', '<=>', '<$>']
    })
    hf_model.resize_token_embeddings(len(hf_tokenizer), pad_to_multiple_of=8)
    model = HookedTransformer.from_pretrained('gpt2', hf_model=hf_model, tokenizer=hf_tokenizer)
```

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/neelnanda-io/transformerlens/issues) in the repo (**required**)

**Comment by neelnanda-io** [comment]
What do you want the new embedding vector to be? Randomly initialised? And
do you want in the unembed, embed, or both?

Either way, this seems a bit niche but fine to have. You can just do this
by creating a new embedding matrix of the new size and copying over the
embeddings of the old tokens, right? I'd be happy to get a PR for the
library doing that

**Comment by JackCai1206** [comment]
Actually, I think it is cleaner to use the above workaround, where I initialize the model and tokenizer from huggingface, use their resize_token_embedding() function, and then initialize HookedTransformer with the huggingface model and tokenizer. This does not immediately work though, because the library is using default model parameters when initializing `d_vocab`, so it is still stuck with the old `d_vocab`. I would have to add an option to pass in the updated model config to the `get_pretrained_model_config` function. Also, this will only work if the tokenizer is initialized with `add_bos_token=True` and resize_token_embedding is called with `pad_to_multiple_of=None`, because otherwise the library will recreate the tokenizer, thus forgetting the added special tokens. This is how I am currently working around this issue, not sure if it is general enough to warrant a PR.

**Comment by neelnanda-io** [comment]
I'm glad you've found a workaround! My guess is this doesn't warrant a PR, so I'm closing this for now
