### ISSUE TITLE
[Proposal] Add benchmarks for error introduced by HookedTransformer

### ISSUE THREAD

**Issue by collingray** [neelnanda-io/TransformerLens#496]
### Proposal 

Add benchmarks for quantifying the logit errors introduced by running a model using HookedTransformer, as compared to running it through HuggingFace's AutoModelForCausalLM. Tests can also be run to measure the error introduced by different HookedTransformer options, such as the data type used, layer norm folding, and weight centering.

I have already implemented this in order to better debug some errors I was seeing with Yi-6B, and so I'm making this issue to understand if people think this is useful enough to be merged, and to see if anyone has any requests/suggestions for improvements.

### Motivation

The two ways this could be useful are:
1. People using TL for research could have a clear understanding of the error introduced
2. People adding new models to TL could have a quick way to test that models are running correctly

### Additional context

An example output showing the tested parameters and metrics

|    | model      | dtype   | options                |         max |        mean |      median |         std |
|---:|:-----------|:--------|:-----------------------|------------:|------------:|------------:|------------:|
|  0 | gpt2       | float16 | unprocessed            | 0.0164795   | 4.17233e-07 | 0           | 3.45707e-05 |
|  1 | gpt2       | float16 | fold_ln                | 0.0174561   | 5.36442e-07 | 0           | 3.70145e-05 |
|  2 | gpt2       | float16 | center_writing_weights | 0.0166016   | 4.17233e-07 | 0           | 3.53456e-05 |
|  3 | gpt2       | float16 | center_unembed         | 0.0144043   | 2.98023e-07 | 0           | 2.71201e-05 |
|  4 | gpt2       | float16 | fold_value_biases      | 0.00939941  | 3.57628e-07 | 0           | 2.563e-05   |
|  5 | gpt2       | float16 | all_options            | 0.0183105   | 3.57628e-07 | 0           | 3.51071e-05 |
|  6 | gpt2       | float32 | unprocessed            | 1.86861e-05 | 5.81105e-10 | 6.22435e-12 | 4.52488e-08 |
|  7 | gpt2       | float32 | fold_ln                | 1.72257e-05 | 5.11322e-10 | 5.22959e-12 | 4.2271e-08  |
|  8 | gpt2       | float32 | center_writing_weights | 2.06828e-05 | 5.90132e-10 | 6.19593e-12 | 4.71539e-08 |
|  9 | gpt2       | float32 | center_unembed         | 7.15256e-06 | 1.83884e-10 | 1.81899e-12 | 1.44107e-08 |
| 10 | gpt2       | float32 | fold_value_biases      | 2.19196e-05 | 5.8077e-10  | 6.19593e-12 | 4.82306e-08 |
| 11 | gpt2       | float32 | all_options            | 5.31971e-06 | 1.66054e-10 | 1.84741e-12 | 1.19176e-08 |
| 12 | mistral-7B | float16 | unprocessed            | 0.00145847  | 4.17223e-08 | 9.28753e-09 | 3.55665e-06 |
| 13 | mistral-7B | float16 | fold_ln                | 0.00136884  | 6.27387e-08 | 9.52886e-09 | 4.3631e-06  |
| 14 | mistral-7B | float16 | center_writing_weights | 0.00145847  | 4.17223e-08 | 9.28753e-09 | 3.55665e-06 |
| 15 | mistral-7B | float16 | center_unembed         | 0.0020767   | 8.70632e-08 | 9.47807e-09 | 6.38039e-06 |
| 16 | mistral-7B | float16 | fold_value_biases      | 0.00145847  | 4.17223e-08 | 9.28753e-09 | 3.55665e-06 |
| 17 | mistral-7B | float16 | all_options            | 0.0020767   | 7.98113e-08 | 9.5058e-09  | 6.09042e-06 |

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/neelnanda-io/transformerlens/issues) in the repo (**required**)

**Comment by Butanium** [comment]
Related weights for gpt2 differs. E.g : 
```py
import torch as th
from transformers import AutoModelForCausalLM
import transformer_lens as tl
hf_model = AutoModelForCausalLM.from_pretrained("gpt2", device_map="cpu")
tl_model = tl.HookedTransformer.from_pretrained("gpt2", device="cpu")
param_tl = list(tl_model.embed.parameters())
param_hf = list(hf_model.transformer.wte.parameters())
print("Shapes: ", [x.shape for x in param_tl], [x.shape for x in param_hf])
print(f"max abs diff: {(param_tl[0] - param_hf[0]).abs().max()}")
```
Loaded pretrained model gpt2 into HookedTransformer
Shapes:  [torch.Size([50257, 768])] [torch.Size([50257, 768])]
max abs diff: 0.011169403791427612
