### ISSUE TITLE
[Proposal] Speed up `!pip install transformer-lens` in colab

### ISSUE THREAD

**Issue by ArthurConmy** [neelnanda-io/TransformerLens#497]
### Proposal 

Currently `!pip install transformer-lens` takes ~a minute in colab. However, a lot of time is spent uninstalling PyTorch 2.1.0 and upgrading. 

I think this is because we pinned PyTorch >2.1.0 [here](https://github.com/neelnanda-io/TransformerLens/pull/457) because of PyTorch bugs on MPS. But this doesn't impact colab.

Ideally, a solution would make `!pip install transformer-lens` use the version of PyTorch colab is shipped with, but demand an upgrade on MPS solutions. I'm out of my depth here though, so would appreciate discussion of how big an issue this is and what solutions we could have!

**Comment by alan-cooney** [comment]
This is possible - https://python-poetry.org/docs/dependency-specification/#using-environment-markers .

Seems like a reasonable thing to do!

**Comment by ArthurConmy** [comment]
Thanks! Sadly I don't think this works out-of-the-box and I'm not sure why

See implementation [here](https://github.com/neelnanda-io/TransformerLens/compare/main...ArthurConmy:TransformerLens:colab-fast-install?expand=1) and then pip seems to realise it can use any `torch` version >=1.10 and that it has a bigger version installed, but just reinstalls torch anyway. I'm quite confused and LLMs did not help!

```bash
$ %pip install git+https://github.com/ArthurConmy/TransformerLens.git@colab-fast-install
...
Requirement already satisfied: torch>=1.10 in /usr/local/lib/python3.10/dist-packages (from transformer-lens==0.0.0) (2.1.0+cu121)
Collecting torch>=1.10 (from transformer-lens==0.0.0)
  Downloading torch-2.1.2-cp310-cp310-manylinux1_x86_64.whl (670.2 MB)
...
```

**Comment by alan-cooney** [comment]
Ah it's probably also a downstream dependency also requiring >2 then? In that case it's probably more hassle than it's worth to find and fix it (and possibly not fixable).

FYI the marker "platform_machine == 'arm64'" catches just M1/M2 I think, so if you did find all the requirement chains it's probably easier to just set that to >=2.1.2 . 

Oh and to add complexity, I'm not sure how installing from github differs from installing from pypi - there may be a subtle difference (e.g. it might be using the poetry lock file for the former).

**Comment by pavanyellow** [comment]
> Thanks! Sadly I don't think this works out-of-the-box and I'm not sure why
> 
> (Implementation reference [here](https://github.com/neelnanda-io/TransformerLens/compare/main...ArthurConmy:TransformerLens:colab-fast-install?expand=1)). `pip` seems to realise it can use any `torch` version >=1.10, and also realise that it has a compatible version installed, but just reinstalls torch anyway. I'm quite confused and LLMs did not help!
> 
> ```shell
> $ %pip install git+https://github.com/ArthurConmy/TransformerLens.git@colab-fast-install
> ...
> Requirement already satisfied: torch>=1.10 in /usr/local/lib/python3.10/dist-packages (from transformer-lens==0.0.0) (2.1.0+cu121)
> Collecting torch>=1.10 (from transformer-lens==0.0.0)
>   Downloading torch-2.1.2-cp310-cp310-manylinux1_x86_64.whl (670.2 MB)
> ...
> ```

@ArthurConmy your implementation seems to work with a small change. #510
