### ISSUE TITLE
Put documentation for abstract_attribute use case

### ISSUE THREAD

**Issue by soniajoseph** [neelnanda-io/TransformerLens#499]
Hello!

I'm adapting this library for vision and it would be super great if the abstract_attribute class had more documentation so I know the logic behind the design decision and whether to implement it or not. Thanks!

https://github.com/neelnanda-io/TransformerLens/blob/829084a53836c5b8b388aa37a5ffce73b6371712/transformer_lens/components.py#L422C1-L423C1

**Comment by soniajoseph** [comment]
@Felhof

**Comment by Felhof** [comment]
Hi Sonjia, I have added a short description of why abstract_attribute is used and a link to documentation [here](https://github.com/neelnanda-io/TransformerLens/pull/508). Does this help, or would you like me to add more information?

**Comment by soniajoseph** [comment]
Yes, thank you!
