### ISSUE TITLE
[Proposal] Add support for Qwen1.5 models

### ISSUE THREAD

**Issue by andyrdt** [neelnanda-io/TransformerLens#506]
### Proposal 

Add support for the recently released Qwen1.5 models ([link](https://qwenlm.github.io/blog/qwen1.5/)).

Should include base and chat models for sizes 0.5B, 1.8B, 4B, 7B, 14B, and 72B.

Their announcement does not mention any architectural changes, so I think this change should be quick/straightforward, but is worth double checking.

### Additional context

See #477 for original Qwen PR.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/neelnanda-io/transformerlens/issues) in the repo (**required**)

**Comment by qwenzo** [comment]
how doesa loading this model for logit attribution methods work? is the following enough? 

```
model = HookedTransformer.from_pretrained(
    "Qwen/Qwen1.5-0.5B-Chat",
    center_unembed=True,
    # Qwen uses RMSNorm
    center_writing_weights=False, 
    fold_value_biases=False,
    fold_ln=True,
    default_padding_side="left",
    device=device,
)
```
