### ISSUE TITLE
[Bug Report] Demos utilizing PySvelte are not able to install

### ISSUE THREAD

**Issue by vashchuko** [neelnanda-io/TransformerLens#530]
**Describe the bug**
I'm running Head_Detector_Demo on the Colab. When I'm running this notebook installation steps, the installation of PySvelte fails without details.

**Code example**
![image](https://github.com/neelnanda-io/TransformerLens/assets/136713300/6e414b10-1b2a-4324-8a7f-e6bef45cbe4e)

**System Info**
Google Colab with Python 3

**Additional context**
I also tried to build it directly on Colab machine.
The result is pretty the same
Obtaining file:///content/PySvelte
  Preparing metadata (setup.py): started
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py): finished with status 'error'
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Is there a specific python version to use?

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/neelnanda-io/TransformerLens/issues) in the repo (**required**)

**Comment by bryce13950** [comment]
This is affecting any demos using PySvelte. The underlying issue has been resolved, and once [this](https://github.com/neelnanda-io/PySvelte/pull/21) pull request is resolved, the issue will be resolved here. For the time being, I will leave this open for anyone else who may have this issue.

For the time being, if you change `%pip install git+https://github.com/neelnanda-io/PySvelte.git` to `%pip install git+https://github.com/austinleedavis/PySvelte-fixColabSetup.git`, you will be able to install the demo and use it.

**Comment by vashchuko** [comment]
Thanks for the answer. I was actually able to run the demo with curcuitsvis library. It is working perfectly fine.

**Comment by bryce13950** [comment]
This has been resolved
