### ISSUE TITLE
[Question] Weight Conversion of GPTJ Model

### ISSUE THREAD

**Issue by NUAAZXY** [neelnanda-io/TransformerLens#531]
### Question

During the process of converting model weights, I encountered some confusion. Why is it necessary to set the weight of ln2 equal to ln1 when extracting the weights of GPTJ? Upon reviewing the code of GPTJ, I noticed that they neither use ln2 nor do they apply ln1 twice.

**Comment by neelnanda-io** [comment]
TransformerLens fits many models into a single consistent architecture.
This assumes, for generality, that there's a separate Ln for attention and
for MLP. GPT-J has a single LN applied once, and this normed residual
stream is then used for both attention and MLP. Ensuring ln1 and ln2 have
the same weights achieves an identical effect in the TL architecture

**Comment by NUAAZXY** [comment]
Thank you for you reply!
