### ISSUE TITLE
[Bug Report] Transformer_lens should be pinned to 1.1.1 for Attribution_Patching demo

### ISSUE THREAD

**Issue by adamkarvonen** [neelnanda-io/TransformerLens#539]
**Describe the bug**
If I click "run all" on this notebook:
https://colab.research.google.com/github/neelnanda-io/TransformerLens/blob/main/demos/Attribution_Patching_Demo.ipynb

It fails with this error:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[<ipython-input-19-a9774221fd88>](https://localhost:8080/#) in <cell line: 19>()
     17     return value.item(), ActivationCache(cache, model), ActivationCache(grad_cache, model)
     18 
---> 19 clean_value, clean_cache, clean_grad_cache = get_cache_fwd_and_bwd(model, clean_tokens, ioi_metric)
     20 print("Clean Value:", clean_value)
     21 print("Clean Activations Cached:", len(clean_cache))

3 frames
[/usr/local/lib/python3.10/dist-packages/transformer_lens/HookedTransformer.py](https://localhost:8080/#) in check_hooks_to_add(self, hook_point, hook_point_name, hook, dir, is_permanent, prepend)
    233             ), f"Cannot add hook {hook_point_name} if use_hook_mlp_in is False"
    234         if hook_point_name.endswith("attn_in"):
--> 235             assert (
    236                 self.cfg.use_attn_in
    237             ), f"Cannot add hook {hook_point_name} if use_attn_in is False"

AssertionError: Cannot add hook blocks.0.hook_attn_in if use_attn_in is False
```
The notebook was made in [this commit ](https://github.com/neelnanda-io/TransformerLens/commit/407f5fefec522bbbab8075934b3c2922b968f058)on Feb 4 2023. On Feb 4, 2023, version 1.1.1 was released. Pinning transformer_lens to 1.1.1 with:

!pip install transformer_lens==1.1.1

Lets the notebook run to the end with no errors.

I also had errors because pysvelte wouldn't install. Based on this issue: https://github.com/neelnanda-io/TransformerLens/issues/530

I fixed it by replacing `%pip install git+https://github.com/neelnanda-io/PySvelte.git` with `%pip install git+https://github.com/austinleedavis/PySvelte-fixColabSetup.git`. It looks like it could also be fixed with this pull request: https://github.com/neelnanda-io/PySvelte/pull/21

I attempted to create a pull request, but after experimentation with nbstripout, manual edits, etc, I was unable to make the change without a 1,085 line diff.

**Code example**
Click Run All on Colab Notebook.

**System Info**
Google Colab, T4 instance

**Additional context**

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/neelnanda-io/TransformerLens/issues) in the repo (**required**)

**Comment by bryce13950** [comment]
The issue with PySvelte is resolved, so no need to change that URL anymore. The demo has also been locked to 1.1.1 for the time being. I will also get it up to date with the current version of TransformerLens, but you shouldn't have any more issues using it as is.
